import { NextRequest, NextResponse } from "next/server";
import { format } from "date-fns";
import { db } from "@/lib/db";
import { formatINR } from "@/lib/money";
import { sheetTotals } from "@/lib/sheets";
import { buildPdf, type PdfSection } from "@/lib/pdfgen";
import { BATCH_TYPE_LABEL, type BatchType } from "@/lib/enums";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function parseIds(json: string): string[] {
  try {
    const v = JSON.parse(json);
    return Array.isArray(v) ? v.map(String) : [];
  } catch {
    return [];
  }
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const dispatch = await db.dispatch.findUnique({ where: { id } });
  if (!dispatch) return NextResponse.json({ error: "not found" }, { status: 404 });

  const label = BATCH_TYPE_LABEL[dispatch.batchType as BatchType] ?? dispatch.batchType;
  const sheetIds = parseIds(dispatch.includedSheetIds);

  const [sheets, trigger] = await Promise.all([
    db.closingSheet.findMany({
      where: { id: { in: sheetIds } },
      include: { project: { include: { producer: true } }, lines: true },
    }),
    db.user.findUnique({ where: { id: dispatch.triggeredById } }),
  ]);

  // Approved/paid reimbursements for the same projects (compiled into the dispatch).
  const projectNames = sheets.map((s) => s.project.name);
  const reimbursements = await db.reimbursement.findMany({
    where: { projectName: { in: projectNames }, status: { in: ["APPROVED", "PAID"] } },
    orderBy: { createdAt: "asc" },
  });

  const sheetsTotal = sheets.reduce((sum, s) => sum + sheetTotals(s.lines).grand, 0);
  const reimbTotal = reimbursements.reduce((sum, r) => sum + r.amount, 0);

  const sections: PdfSection[] = [
    {
      heading: "Closing sheets",
      table: {
        columns: ["Project", "Producer", "Total"],
        widths: [0.5, 0.3, 0.2],
        align: ["left", "left", "right"],
        rows: [
          ...sheets.map((s) => [
            s.project.name,
            s.project.producer.name,
            formatINR(sheetTotals(s.lines).grand),
          ]),
          ["", "Subtotal", formatINR(sheetsTotal)],
        ],
      },
    },
  ];

  sections.push({
    heading: "Reimbursements",
    table: {
      columns: ["Project", "Description", "Mode", "Amount"],
      widths: [0.32, 0.4, 0.13, 0.15],
      align: ["left", "left", "left", "right"],
      rows: reimbursements.length
        ? [
            ...reimbursements.map((r) => [
              r.projectName ?? "—",
              r.description ?? "—",
              r.paymentMode,
              formatINR(r.amount),
            ]),
            ["", "", "Subtotal", formatINR(reimbTotal)],
          ]
        : [["—", "No approved reimbursements for these projects", "", ""]],
    },
  });

  const pdf = await buildPdf({
    title: `${label} — Dispatch Summary`,
    subtitle: "Revolio Media Pvt Ltd · sent to accounts",
    meta: [
      ["Dispatched by", trigger?.name ?? "—"],
      ["Dispatched at", format(dispatch.triggeredAt, "d MMM yyyy, h:mm a")],
      ["Closing sheets", String(sheets.length)],
      ["Reimbursements", String(reimbursements.length)],
      ["Grand total", formatINR(sheetsTotal + reimbTotal)],
    ],
    sections,
    footer: dispatch.notes
      ? `Note: ${dispatch.notes} · Generated by Revolio.`
      : "Generated by Revolio.",
  });

  return new NextResponse(Buffer.from(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="dispatch-${label.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}.pdf"`,
    },
  });
}
