import { NextRequest, NextResponse } from "next/server";
import { format } from "date-fns";
import { db } from "@/lib/db";
import { formatINR } from "@/lib/money";
import { buildPdf } from "@/lib/pdfgen";
import { PAYMENT_MODE_LABEL, INVOICE_STATUS_LABEL } from "@/lib/enums";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const inv = await db.invoice.findUnique({
    where: { id },
    include: { vendor: true, closingSheet: { include: { project: true } } },
  });
  if (!inv) return NextResponse.json({ error: "not found" }, { status: 404 });

  const meta: [string, string][] = [
    ["Vendor", inv.vendor?.name ?? "—"],
    ["Project", inv.closingSheet?.project.name ?? inv.projectName ?? "—"],
    ["Category", inv.category ?? "—"],
    ["Invoice date", inv.shootDate ? format(inv.shootDate, "d MMM yyyy") : "—"],
    ["PAN", inv.pan ?? "—"],
    ["GSTIN", inv.gstin ?? (inv.gstApplicable ? "— (applicable)" : "Exempt")],
    ["Payment mode", inv.paymentMode ? (PAYMENT_MODE_LABEL[inv.paymentMode as keyof typeof PAYMENT_MODE_LABEL] ?? inv.paymentMode) : "—"],
    ["Status", INVOICE_STATUS_LABEL[inv.status as keyof typeof INVOICE_STATUS_LABEL] ?? inv.status],
  ];

  const pdf = await buildPdf({
    title: "Invoice",
    subtitle: "Revolio Media Pvt Ltd",
    meta,
    sections: [
      {
        table: {
          columns: ["Description", "Amount"],
          widths: [0.7, 0.3],
          align: ["left", "right"],
          rows: [
            [`${inv.category ?? "Services"} — ${inv.vendor?.name ?? "vendor"}`, formatINR(inv.amount)],
            ["Total", formatINR(inv.amount)],
          ],
        },
      },
    ],
    footer: "Generated by Revolio · internal record, not a signed tax document.",
  });

  const filename = `invoice-${(inv.vendor?.name ?? "vendor").replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}.pdf`;
  return new NextResponse(Buffer.from(pdf), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="${filename}"`,
    },
  });
}
